[yobi]
numerator = "1024^8"
denominator ="1"

[zebi]
numerator = "1024^7"
denominator ="1"

[exbi]
numerator = "1024^6"
denominator ="1"

[pebi]
numerator = "1024^5"
denominator ="1"

[tebi]
numerator = "1024^4"
denominator ="1"

[gibi]
numerator = "1024^3"
denominator ="1"

[mebi]
numerator = "1024^2"
denominator ="1"

[kibi]
numerator = "1024^1"
denominator ="1"
